### ISSUE TITLE
Source code Ino

### ISSUE THREAD

**Issue by peastuti** [johnadali/DeviceTwinsExample#1]
Hello there, thank you for this example. Can you share with us the .ino code as explained in this video? 
https://www.youtube.com/watch?v=vrhhQhqf2fE

Cheers

**Comment by johnadali** [comment]
Hello there!
   The file is located at [DeviceTwinsExample/DeviceTwinsBackend/DeviceTwinsTest/Device/device.ino](https://github.com/johnadali/DeviceTwinsExample/blob/master/DeviceTwinsBackend/DeviceTwinsTest/Device/device.ino) in the repo. Let me know if you can't see it.

Thanks.
